export const recipes = [
    "pasta",
    "cauliflower",
    "vegetarian",
    "cuisine",
    "coffeebean",
    "tomato",
    "cheese",
    "egg",
    "meat",
    "paneer",
    "chicken",
    "sandwich",
    "seafood",
    "biryani",
    "potato",
    "rice",
    "taco",
    "rolls",
    "pancake",
  ];
  